### PR TITLE
upgrade dependencies for outputs

### PR DESCRIPTION
**Pull request by rgbkrk**
Upgrading outputs packages to use the latest from the other nteract repos.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Not sure why snapshots are failing in CI but not locally.

image

**Comment by rgbkrk** [comment]
Only vega is giving me issue

image

**Comment by captainsafia** [comment]
@rgbkrk Can you update the commits to use the conventional commit style so we can take advantage of auto-release here?

See https://github.com/nteract/nteract/discussions/5568

**Comment by rgbkrk** [comment]
Totally, can do!

**Comment by rgbkrk** [comment]
Conventional commit style is a go! Glad we're back into it. 😄

**Comment by captainsafia** [comment]
@rgbkrk I was able to repro the snapshot failures in a Codespace so pushed a commit to make the necessary updates.

**Comment by rgbkrk** [comment]
Thank you!

**Pull request merged**
